# Generated by Django 5.0.7 on 2024-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cocktail',
            name='preparation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
