# Generated by Django 5.0.7 on 2024-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0003_remove_cocktail_ingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='label',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='special',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
